### ISSUE TITLE
Extending the instructions for using the library in Xcode

### ISSUE THREAD

**Issue by caldrian** [steveisok/library-mode-sample#1]
Hello Steve,

Thank you setting up this repository!
Unfortunately I'm still not sure how to add this `ManagedProject` to an iOS project. Could you please provide more specific steps?

After running the `dotnet publish` command I have the following files:
A `libManagedProject.dylib` in a folder named `Bundle` next to various source code files.
```
./ManagedProject/bin/Release/net9.0/ios{,simulator}-arm64/Bundle/{libManagedProject.dylib,*.h,*.m,*.c,*.txt}
```
In the `publish` folder there are several `.dylib`, `.a` and `.dll` files (but no `libManagedProject.dylib`):
```
./ManagedProject/bin/Release/net9.0/ios{,simulator}-arm64/publish/libSystem.*.{a,dylib}
./ManagedProject/bin/Release/net9.0/ios{,simulator}-arm64/publish/libmono-component*.a
./ManagedProject/bin/Release/net9.0/ios{,simulator}-arm64/publish/libmonosgen-2.0.{a,dylib}
```

Which of these files need to be linked into the iOS app target?
Do I also have to include files as bundle resource?
Is there no public header file? I'm not able to import any module and so `SayHello();` doesn't compile with an undeclared function error.

**Comment by caldrian** [comment]
My missing piece was a module.map file
```
module ManagedProject {
    header "ManagedProject.h"
    export *
}
```
and a header file ManagedProject.h
```
void SayHello();
```

**Comment by AlexeiNaabal** [comment]
> My missing piece was a module.map file
> 
> ```
> module ManagedProject {
>     header "ManagedProject.h"
>     export *
> }
> ```
> 
> and a header file ManagedProject.h
> 
> ```
> void SayHello();
> ```

Would you please post a simple instruction?

From the publish configuration, we have to publish the nativelib as an self-contained exe, thus in theory only the final dylib is needed, and we can decorate the functions with extern with the dylib linked, I believe
